tap "homebrew/bundle"
brew "berkeley-db", link: true
brew "cmake"
brew "coreutils"
brew "fzf"
brew "gcc"
brew "ghq"
brew "git"
brew "htop"
brew "nodebrew"
brew "sqlite"
brew "tmux"
brew "vim"
brew "zsh-autosuggestions"
brew "zsh-completions"
if OS.mac?
  cask "alfred"
  cask "brave-browser"
  cask "google-chrome"
  cask "macdown"
  cask "rectangle"
  cask "tunnelblick"
  cask "visual-studio-code"
  cask "wireshark"
  cask "xquartz"
end
